### ISSUE TITLE
Onboard Julia

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-RPM#109]
### Goals
* Provide Julia with enough context about the project, partner, product, and team to be able to engage effectively.

### Tasks
- [x] Prepare an onboarding doc that is UX/Design-specific
- [x] Meet with Julia to walk through things, answer questions
- [x] Update meeting invites to include Julia as appropriate
- [x] Ensure Julia has access to the tools we use

**Comment by ninamak** [comment]
[UX/Design Onboarding Doc](https://docs.google.com/document/d/1dTe12ZsUzAHjrXwCehRdckPMOnPe66S-kHDLT6Hu3ik/edit)

**Comment by juliaklindpaintner** [comment]
I think we're good on this task for now!
