### ISSUE TITLE
[4] Move repo to HHS GH (public)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-RPM#83]
### Goals
* Start development in our destination GH repo

### Tasks
- [ ] Reach out to Domenic and clarify our new request (we previously asked for a private repo but no longer think we need that)
- [ ] Add the appropriate collaborators to the org and repo
- [ ] Ask 18F GH Admins for help transferring the repo (we do not have that ability enabled)
- [ ] Do the transfer (repo and project board)

### Conditions of Acceptance
* Each of us on the team (inc Sheila) can access a public HHS GH repo that contains all the docs and project board from the 18F/OPRE-Unicorn repo
* Team has write access permissions

### Resources
* [GitHub Docs: Transferring a repository](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository)

**Comment by alexsoble** [comment]
@ninamak Added a resource on transferring repositories that might be helpful!

**Comment by alexsoble** [comment]
Asked our GitHub admins what the preferred flow for this is.

**Comment by alexsoble** [comment]
Scheduled an email to go out to Domenic tomorrow morning to find a good time for the repo transfer.

**Comment by alexsoble** [comment]
Set up meeting for this Thursday between TTS GitHub admin and HHS GitHub admin to transfer the repo.

**Comment by alexsoble** [comment]
Oh hey! I think this is done! https://github.com/HHS/OPRE-RPM

**Comment by alexsoble** [comment]
@ninamak Do you have write access? Can you add issues, comments, propose changes?

**Comment by ninamak** [comment]
Looks like everything works!
